[env:arduino_nano_esp32]
platform = espressif32 @ ^6.13.0
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
monitor_filters = direct

build_flags =
    -I src
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DPIO_FRAMEWORK_ARDUINO_NO_PIN_REMAP
    -UARDUINO_ARCH_ESP32

lib_deps =
    knolleary/PubSubClient @ ^2.8
    kosme/arduinoFFT @ ^2.0.1