[env:heltec_wifi_lora_32_V3]
platform = espressif32 @ 7.0.0
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags = -I src

lib_deps =
    knolleary/PubSubClient @ ^2.8
    kosme/arduinoFFT @ ^2.0.4
    adafruit/Adafruit INA219 @ ^1.2.3
    ropg/Heltec_ESP32_LoRa_v3 @ ^0.9.2
    ropg/LoRaWAN_ESP32 @ ^1.2.0
